//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_NL_BANK
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCTransaction
    {
        public int CTransID { get; set; }
        public string CTransType { get; set; }
        public Nullable<decimal> CAmount { get; set; }
        public string CAccountNo { get; set; }
        public Nullable<System.DateTime> CDateCreated { get; set; }
    }
}
