//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_NL_BANK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NL_BankEntities : DbContext
    {
        public NL_BankEntities()
            : base("name=NL_BankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCTransaction> ACCTransactions { get; set; }
        public virtual DbSet<BankAccountMaster> BankAccountMasters { get; set; }
        public virtual DbSet<BANK_INCOME> BANK_INCOME { get; set; }
        public virtual DbSet<V_ACCTransactions> V_ACCTransactions { get; set; }
        public virtual DbSet<V_Bank_Income> V_Bank_Income { get; set; }
        public virtual DbSet<V_BankAccountMaster> V_BankAccountMaster { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
