//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary_NL_BANK
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int USERID { get; set; }
        public string USER_FNAME { get; set; }
        public string USER_LNAME { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string Role { get; set; }
        public string IBANAccountNo { get; set; }
    }
}
